-- Drop na ordem certa por causa de FK
DROP TABLE IF EXISTS T_GS_USUARIO_PAPEL;
DROP TABLE IF EXISTS T_GS_RECOMENDACAO_IA;
DROP TABLE IF EXISTS T_GS_AGG_INDICE_SEMANAL;
DROP TABLE IF EXISTS T_GS_CONFIG_GESTOR;
DROP TABLE IF EXISTS T_GS_CHECKIN;
DROP TABLE IF EXISTS T_GS_USUARIO;
DROP TABLE IF EXISTS T_GS_PAPEL;
DROP TABLE IF EXISTS T_GS_TIME;
DROP TABLE IF EXISTS T_GS_EMPRESA;

----------------------------------------------------
-- EMPRESA
----------------------------------------------------
CREATE TABLE T_GS_EMPRESA (
    id_empresa      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_empresa      VARCHAR(150) NOT NULL,
    cnpj            VARCHAR(18),
    email_contato   VARCHAR(150),
    dt_cadastro     TIMESTAMP,
    CONSTRAINT uk_empresa_nome UNIQUE (nm_empresa)
);

----------------------------------------------------
-- TIME / EQUIPE
----------------------------------------------------
CREATE TABLE T_GS_TIME (
    id_time     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa  BIGINT NOT NULL,
    nm_time     VARCHAR(120) NOT NULL,
    ds_time     VARCHAR(300),
    CONSTRAINT fk_time_empresa
        FOREIGN KEY (id_empresa) REFERENCES T_GS_EMPRESA(id_empresa),
    CONSTRAINT uk_time_empresa_nome UNIQUE (id_empresa, nm_time)
);

----------------------------------------------------
-- PAPEL
----------------------------------------------------
CREATE TABLE T_GS_PAPEL (
    id_papel    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_papel    VARCHAR(30) NOT NULL,
    ds_papel    VARCHAR(150),
    CONSTRAINT uk_papel_codigo UNIQUE (cd_papel)
);

----------------------------------------------------
-- USUARIO
----------------------------------------------------
CREATE TABLE T_GS_USUARIO (
    id_usuario      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa      BIGINT NOT NULL,
    id_time         BIGINT,
    nm_usuario      VARCHAR(150) NOT NULL,
    email           VARCHAR(150) NOT NULL,
    fl_ativo        CHAR(1),
    fuso_horario    VARCHAR(60),
    dt_cadastro     TIMESTAMP,
    CONSTRAINT fk_usuario_empresa
        FOREIGN KEY (id_empresa) REFERENCES T_GS_EMPRESA(id_empresa),
    CONSTRAINT fk_usuario_time
        FOREIGN KEY (id_time) REFERENCES T_GS_TIME(id_time),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

----------------------------------------------------
-- USUARIO_PAPEL
----------------------------------------------------
CREATE TABLE T_GS_USUARIO_PAPEL (
    id_usuario_papel BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       BIGINT NOT NULL,
    id_papel         BIGINT NOT NULL,
    CONSTRAINT fk_up_usuario
        FOREIGN KEY (id_usuario) REFERENCES T_GS_USUARIO(id_usuario),
    CONSTRAINT fk_up_papel
        FOREIGN KEY (id_papel) REFERENCES T_GS_PAPEL(id_papel),
    CONSTRAINT uk_usuario_papel UNIQUE (id_usuario, id_papel)
);

----------------------------------------------------
-- CHECKIN
----------------------------------------------------
CREATE TABLE T_GS_CHECKIN (
    id_checkin        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        BIGINT NOT NULL,
    dt_checkin        TIMESTAMP NOT NULL,
    vl_humor          INT NOT NULL,
    vl_foco           INT NOT NULL,
    minutos_pausas    INT,
    horas_trabalhadas DOUBLE,
    ds_observacoes    CLOB,
    tags              VARCHAR(200),
    origem            VARCHAR(20),
    CONSTRAINT fk_checkin_usuario
        FOREIGN KEY (id_usuario) REFERENCES T_GS_USUARIO(id_usuario)
);

----------------------------------------------------
-- CONFIG_GESTOR
----------------------------------------------------
CREATE TABLE T_GS_CONFIG_GESTOR (
    id_config_gestor  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa        BIGINT NOT NULL,
    id_time           BIGINT,
    limiar_alerta     DOUBLE NOT NULL,
    janela_dias       INT NOT NULL,
    fl_anonimizado    CHAR(1) NOT NULL,
    CONSTRAINT fk_cfg_empresa
        FOREIGN KEY (id_empresa) REFERENCES T_GS_EMPRESA(id_empresa),
    CONSTRAINT fk_cfg_time
        FOREIGN KEY (id_time) REFERENCES T_GS_TIME(id_time)
);

----------------------------------------------------
-- AGG_INDICE_SEMANAL
----------------------------------------------------
CREATE TABLE T_GS_AGG_INDICE_SEMANAL (
    id_agg           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa       BIGINT NOT NULL,
    id_time          BIGINT,
    dt_inicio_semana DATE NOT NULL,
    qtd_usuarios     INT NOT NULL,
    media_indice     DOUBLE NOT NULL,
    media_risco      DOUBLE NOT NULL,
    dt_geracao       TIMESTAMP,
    CONSTRAINT fk_agg_empresa
        FOREIGN KEY (id_empresa) REFERENCES T_GS_EMPRESA(id_empresa),
    CONSTRAINT fk_agg_time
        FOREIGN KEY (id_time) REFERENCES T_GS_TIME(id_time)
);

----------------------------------------------------
-- RECOMENDACAO_IA
----------------------------------------------------
CREATE TABLE T_GS_RECOMENDACAO_IA (
    id_recomendacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario      BIGINT NOT NULL,
    dt_criacao      TIMESTAMP NOT NULL,
    dt_validade     DATE NOT NULL,
    categoria       VARCHAR(50) NOT NULL,
    descricao       VARCHAR(1000) NOT NULL,
    origem          VARCHAR(30),

    CONSTRAINT fk_recomendacao_usuario
        FOREIGN KEY (id_usuario)
            REFERENCES T_GS_USUARIO(id_usuario)
);